import type { BudgetCategory, Vendor, Account, Transaction } from "../../types";

export const dummyCategories: BudgetCategory[] = [
  {
    id: 1,
    name: "Food & Dining",
    budgeted: 500,
    color: "#3b82f6",
  },
  {
    id: 2, 
    name: "Transportation",
    budgeted: 200,
    color: "#f59e42",
  },
  {
    id: 3,
    name: "Entertainment",
    budgeted: 150,
    color: "#a21caf",
  },
  {
    id: 4,
    name: "Shopping",
    budgeted: 300,
    color: "#fbbf24",
  },
  {
    id: 5,
    name: "Utilities",
    budgeted: 250,
    color: "#06b6d4",
  },
  {
    id: 6,
    name: "Healthcare",
    budgeted: 100,
    color: "#22c55e",
  },
  {
    id: 7,
    name: "Income",
    budgeted: 1000,
    color: "#10b981",
  },
];

export const dummyVendors: Vendor[] = [
  { id: 1, name: "Whole Foods Market", website: "https://www.wholefoodsmarket.com" },
  { id: 2, name: "Tech Corp Inc" },
  { id: 3, name: "Shell", website: "https://www.shell.com" },
  { id: 4, name: "Netflix", website: "https://www.netflix.com" },
  { id: 5, name: "Starbucks", website: "https://www.starbucks.com" },
  { id: 6, name: "Pacific Gas & Electric", website: "https://www.pge.com" },
  { id: 7, name: "Design Studio LLC" },
  { id: 8, name: "Amazon", website: "https://www.amazon.com" },
];

export const dummyAccounts: Account[] = [
  { id: 1, name: "Chase Checking", type: "checking" },
  { id: 2, name: "Chase Credit Card", type: "credit" },
  { id: 3, name: "Venmo", type: "venmo" },
];

export const dummyTransactions: Transaction[] = [
  {
    id: 1,
    description: "Grocery shopping",
    vendorId: 1,
    categoryId: 1,
    amount: -89.45,
    date: "2024-01-15",
    type: "expense",
    notes: "Weekly groceries including organic produce",
    tags: ["groceries", "organic"],
    accountId: 1,
    recurring: false,
    status: "completed",
  },
  {
    id: 2,
    description: "Salary deposit",
    vendorId: 2,
    categoryId: 7, // Using Food & Dining as a placeholder since we don't have Income category in dashboard
    amount: 4500.00,
    date: "2024-01-15",
    type: "income",
    notes: "Monthly salary payment",
    tags: ["salary", "income"],
    accountId: 1,
    recurring: true,
    status: "completed",
  },
  {
    id: 3,
    description: "Gas station",
    vendorId: 3,
    categoryId: 2,
    amount: -45.67,
    date: "2024-01-14",
    type: "expense",
    notes: "Full tank of gas",
    tags: ["gas", "fuel"],
    accountId: 1,
    recurring: false,
    status: "completed",
  },
  {
    id: 4,
    description: "Netflix subscription",
    vendorId: 4,
    categoryId: 3,
    amount: -15.99,
    date: "2024-01-13",
    type: "expense",
    notes: "Monthly streaming subscription",
    tags: ["streaming", "entertainment"],
    accountId: 2,
    recurring: true,
    status: "completed",
  },
  {
    id: 5,
    description: "Coffee shop",
    vendorId: 5,
    categoryId: 1,
    amount: -6.50,
    date: "2024-01-12",
    type: "expense",
    notes: "Large latte with oat milk",
    tags: ["coffee", "drinks"],
    accountId: 2,
    recurring: false,
    status: "completed",
  },
  {
    id: 6,
    description: "Electric bill",
    vendorId: 6,
    categoryId: 5,
    amount: -127.89,
    date: "2024-01-10",
    type: "expense",
    notes: "Monthly electricity bill",
    tags: ["utilities", "electricity"],
    accountId: 1,
    recurring: true,
    status: "completed",
  },
      {
      id: 7,
      description: "Freelance project",
      vendorId: 7,
      categoryId: 7, // Income category
      amount: 1200.00,
      date: "2024-01-08",
      type: "income",
      notes: "Logo design project completion",
      tags: ["freelance", "design"],
      accountId: 1,
      recurring: false,
      status: "completed",
    },
  {
    id: 8,
    description: "Amazon purchase",
    vendorId: 8,
    categoryId: 4,
    amount: -67.23,
    date: "2024-01-07",
    type: "expense",
    notes: "Books and office supplies",
    tags: ["books", "office"],
    accountId: 2,
    recurring: false,
    status: "completed",
  },
];
